INSERT INTO Releases (id, name, genre, performer, year) VALUES (1, "Year of the Car", "pop", "Al Stewart", 1976)
INSERT INTO Releases (id, name, genre, performer, year) VALUES (2, "Tales of Mystery and Imagination", "rock", "The Alan Parsons Project", 1976)
INSERT INTO Releases (id, name, genre, performer, year) VALUES (3, "The Kick Inside", "pop", "Kate Bush", 1978)
INSERT INTO Releases (id, name, genre, performer, year) VALUES (4, "From the Album of the Same Name", "rock", "Pilot", 1974)

INSERT INTO Personnel (name, role, release_id) VALUES ("Al Stewart", "vocals, guitar", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Peter White", "guitar, keyboards", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Tim Renwick", "guitar", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Peter Wood", "keyboards", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Don Lobster", "keyboards", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("George Ford", "bass guitar", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Stuart Elliot", "drums, percussion, backing vocals", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Bobby Price", "violin", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Marion Driscoll", "triangle", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Phil Kenzie", "alto saxophone", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("David Pack", "backing vocals", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("John Perry", "backing vocals", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Tony Rivers", "backing vocals", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Graham Smith", "harmonica", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Andrew Powell", "string arranger", 1)
INSERT INTO Personnel (name, role, release_id) VALUES ("Alan Parsons", "producer", 1)

INSERT INTO Personnel (name, role, release_id) VALUES ("Alan Parsons", "keyboards, guitars, backing vocals, producer", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Eric Woolfson", "keyboards, vocals", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Ian Bairnson", "guitars", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("John Leach", "combalom, kantele", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Billy Lyall", "Keyboards, drums, glockenspiel", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Les Hurdle", "bass guitar", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Francis Monkman", "keyboards", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Christopher North", "keyboards", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("David Pack", "guitars", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("David Paton", "guitars, bass", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Kevin Peek", "guitars", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Joe Puerta", "bass guitar", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Daryl Runswick", "double bass", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Stuart Tosh", "drums, percussion", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Arthur Brown", "vocals", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("John Miles", "vocals", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Jack Harris", "backing vocals", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Terry Sylvester", "backing vocals", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Leonard Whiting", "vocals", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Smokey Parsons", "vocals", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("David Katz", "violin, orchestra leader", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("Andrew Powell", "orchestral and choir arrangements", 2)
INSERT INTO Personnel (name, role, release_id) VALUES ("The English Chorale", "choir", 2)

INSERT INTO Personnel (name, role, release_id) VALUES ("Kate Bush", "vocals, piano", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Andrew Powell", "keyboards, bass guitar, producer", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Duncan Mackay", "keyboards", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Ian Bairnson", "guitars, backing vocals", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("David Paton", "bass guitar, acoustic guitar, backing vocals", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Stuart Elliot", "drums, percussion", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Alan Skidmore", "tenor saxophone", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Paul Keogh", "guitars", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Alan Parker", "acoustic guitar", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Bruce Lynch", "bass guitar", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Barry de Souza", "drums", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Morris Pert", "percussion", 3)
INSERT INTO Personnel (name, role, release_id) VALUES ("Paddy Bush", "mandolin, backing vocals", 3)

INSERT INTO Personnel (name, role, release_id) VALUES ("David Paton", "vocals, bass", 4)
INSERT INTO Personnel (name, role, release_id) VALUES ("Billy Lyall", "keyboards, backing vocals", 4)
INSERT INTO Personnel (name, role, release_id) VALUES ("Stuart Tosh", "drums, backing vocals", 4)
INSERT INTO Personnel (name, role, release_id) VALUES ("Ian Bairnson", "guitar", 4)
INSERT INTO Personnel (name, role, release_id) VALUES ("Nick Heath", "backing vocals", 4)
INSERT INTO Personnel (name, role, release_id) VALUES ("David Mason", "trumpet", 4)
INSERT INTO Personnel (name, role, release_id) VALUES ("Richard Hewson", "orchestral arrangements", 4)
INSERT INTO Personnel (name, role, release_id) VALUES ("Alan Parsons", "producer", 4)